# Generated by Django 5.1.5 on 2025-02-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='timestamp',
        ),
    ]
